dmm-team-grazie/dmm-naganocake

app/controllers/public/items_controller.rb

[Test] test1

---

app/views/public/items/index.html.erb

[Fix] view file, controller file

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
app/views/public/items/index.html.erb

application.scss, application.jsに追記しました。

[Add] Bootstrap

---

app/views/admins/sessions/new.html.erb

[update]ログイン画面編集

---

app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/input.html.erb
app/views/public/orders/show.html.erb

[add]Order

---

app/views/public/cart_items/index.html.erb

[add]カート一覧画面

---

app/controllers/cart_items_controller.rb
app/views/public/cart_items/index.html.erb
config/initializers/devise.rb

devise.rbファイルの変更
cartitemsコントローラーアクション追記
cartitems viewファイル追記

[update]devise.rbファイル変更

---

app/assets/stylesheets/orders.scss
app/controllers/public/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/hinann.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/input.html.erb
app/views/public/orders/show.html.erb

order.scss に少しcss追加
全七つのviewスタイリング7割完成
コントローラーも少し書いてますがコメントアウトしてます

[update Order] view デザイン

---

app/controllers/admin/genres_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/admins/sessions/new.html.erb
app/views/genres/index.html.erb

Admin genre

---

app/assets/stylesheets/application.scss
app/controllers/public/items_controller.rb
app/models/item.rb
app/views/public/items/show.html.erb

[Update] some view files of item

---

app/assets/stylesheets/members.scss
app/views/members/registrations/new.html.erb
app/views/members/sessions/new.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/members/show.html.erb

[add]scss追加

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/orders.scss
app/controllers/admin/orders_controller.rb
app/controllers/public/orders_controller.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/hinann.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
app/views/public/orders/thanks.html.erb
config/application.rb
config/locales/ja.yml
db/seeds.rb

view全般
config.app(localeのja)
担当model
担当cntroller

update Orders 

---

app/assets/stylesheets/orders.scss
app/controllers/admin/orders_controller.rb
app/controllers/public/orders_controller.rb
app/helpers/orders_helper.rb
app/models/order.rb
app/models/order_detail.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/hinann.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
config/locales/ja.yml

新しく計算用のメソッド（order関連のmodelとhelper)
viewをhtml→ruby方式に当てハメ

[add]calculation methods, [change]views

---

app/assets/stylesheets/application.scss
app/controllers/admin/orders_controller.rb
app/controllers/public/orders_controller.rb
app/views/admin/orders/index.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb

[add] bit change of all

---

app/assets/stylesheets/public/items.scss
app/controllers/admin/items_controller.rb
app/controllers/public/cart_items_controller.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/show.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb

Item [Fix] some files

---

app/controllers/public/orders_controller.rb
app/views/public/orders/confirm.html.erb
app/views/public/orders/new.html.erb

エラーや機能不具合
・address_infoを含んだf.collection_select (newページ
・合計金額の計算（メソッドは作ったが動かない）
・newで入れた支払い情報や住所がconfirmで表示されない
・購入確定でsaveが働かない（@orderが動いていない？

[update]new/confirm view/controller/model

---

app/assets/stylesheets/application.scss
app/controllers/public/genres_controller.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/public/genres/show.html.erb
app/views/public/items/_genre_index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
config/initializers/assets.rb

Item [Update] some view files, config file

---

app/assets/stylesheets/cart_items.scss
app/assets/stylesheets/members.scss
app/controllers/admin/members_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/members_controller.rb
app/models/member.rb
app/views/admin/members/index.html.erb
app/views/admin/members/show.html.erb
app/views/members/registrations/new.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/members/show.html.erb
config/locales/devise.en.yml
config/locales/ja.yml

・ja.ymlファイル更新
・cartitem index更新
・cartitem css更新

update some files

---

app/assets/stylesheets/addresses.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/homes.scss
app/assets/stylesheets/items.scss
app/controllers/admin/items_controller.rb
app/controllers/public/addresses_controller.rb
app/models/address.rb
app/models/item.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/layouts/application.html.erb
app/views/public/addresses/edit.html.erb
app/views/public/addresses/index.html.erb
app/views/public/genres/show.html.erb
app/views/public/homes/top.html.erb
app/views/public/items/_genre_index.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
db/migrate/20200525203900_change_column_to_item.rb
db/schema.rb

Item [Update] some scss

---

app/controllers/admin/genres_controller.rb
app/views/admin/admins/top.html.erb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb

[update] レイアウト

---

app/controllers/admin/admins_controller.rb
app/views/admin/admins/top.html.erb
app/views/admin/genres/index.html.erb

[update]管理者top画面編集

---

app/views/admin/members/index.html.erb
app/views/public/cart_items/index.html.erb

[fix]cartitem/index,scss

---

app/controllers/admin/orders_controller.rb
app/controllers/public/members_controller.rb
app/controllers/public/orders_controller.rb
app/views/admin/admins/top.html.erb
app/views/admin/members/show.html.erb
app/views/admin/orders/member.html.erb
app/views/admin/orders/today.html.erb
app/views/public/members/show.html.erb
app/views/public/orders/member.html.erb
config/routes.rb

最新版でテストをしたいのでチェックお願いします。
皆さんはpullしなくてもテストはできると思います。

[Update] routes, order page

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/homes_controller.rb
app/controllers/public/members_controller.rb

[add]public/member
